spring:
  profiles:
    active: local
---
spring:
  profiles: local
  local:
    kafka:
      topic: local-kafka-topic
  kafka:
    template:
      default-topic: default-kafka-topic
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094