spring:
  profiles:
    active: local
---
spring:
  profiles: local
  local:
    kafka:
      topic: local-library-events
  kafka:
    template:
      default-topic: default-library-events
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 9
        retry.backoff.ms: 1000
    admin:
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094